### ISSUE TITLE
Add ability to set CategoryID

### ISSUE THREAD

**Issue by Dam-35** [joshwolff1/spontit_api#2]
Hi,
Thanks for Spontit, we use it for testing purposes and it's great.
One thing would be very usefull for us : it would be able to define the category of the notification sent, as described in the link below.
https://developer.apple.com/library/archive/documentation/CoreBluetooth/Reference/AppleNotificationCenterServiceSpecification/Appendix/Appendix.html#//apple_ref/doc/uid/TP40013460-CH3-SW2

**Comment by joshwolff1** [comment]
Hi Dam-35!

That's great to hear! I just looked into your request a bit, and it seems like the CategoryID you linked might be only for bluetooth applications. I'm not sure how that would work just yet, but it might.

However, there is another type of CategoryID (AKA a thread-id) that is more common and is used to group notifications.

![IMG_1998](https://user-images.githubusercontent.com/28893844/84408605-308ff500-abc1-11ea-8cbe-e94c178dfab8.jpg)

Would you mind telling me a bit more about your use case so that I can understand what you need?

Thank you,
Josh

**Comment by Dam-35** [comment]
Hi Josh
Thanks for your quick reply.
Our use case is the following.
We're a software testing team, mostly working with mobile apps and also some connected devices (e.g. watches, fitness trackers...). Most of our tests are automated.
So, when testing connected objects, we want to check if notifications sent on phones are also displayed (or not) on those objects.
Spontit is perfect for us as we just have install the app on mobile phones we want to test, no complex setup.

The only detail is that iOS has different Categories of notifications : some of them can be handled differently by applications or their connected objects.
So it would be very intersting for us to be able to set the category when pushing the notification.
(don't know if it's possible, I have very little knoweledge of iOS an ANCS ! )

**Comment by joshwolff1** [comment]
Thank you for the detailed reply. I'd be more than happy to make this work provided it is possible and allowed by Apple App Store Guidelines.

For my further understanding, what do you expect to happen when you change the category of the notification and send it to one of these devices? Could you give me an example of a category you would like to use and what happens when we change the notification to this category?

Could you also give me a list of devices that you're testing on? We currently only support the iOS devices, iPhone and iPad, but are open to supporting more such as Apple Watch, in the future.

**Comment by joshwolff1** [comment]
Hi Dam,

I am closing this because further details were not provided and your original request is not possible, to my knowledge.

Feel free to open a new issue if you would like to clarify and I'd be more than happy to help!

Cheers,
Josh

**Comment by Dam-35** [comment]
Hi Josh,
Yes, no problem, sorry for not providing details, I don't have much time those days...
I'll open a new issue more detailed as soon as I'll have time to provide all informations and use case.

**Comment by joshwolff1** [comment]
Ok, great! I'm looking forward to it
